title: Mixed-Precision Multigrid Solvers for PDEs
url: "https://tani843.github.io"
baseurl: "/Mixed_Precision_Multigrid_Solvers_for_PDEs"

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

defaults:
  - scope: { path: "" }
    values: { layout: default }