title: "Mixed-Precision Multigrid Solvers for PDEs"
description: "High-performance GPU-accelerated multigrid methods"
url: "https://tani843.github.io"
baseurl: "/Mixed_Precision_Multigrid_Solvers_for_PDEs"

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock