# Jekyll Configuration for Mixed-Precision Multigrid Solvers

# Site settings
title: "Mixed-Precision Multigrid Solvers for PDEs"
description: >-
  High-performance numerical methods combining multigrid techniques with
  mixed-precision arithmetic for efficient PDE solving on modern hardware.
baseurl: "/Mixed_Precision_Multigrid_Solvers_for_PDEs" # CRITICAL: project site subpath
url: "https://tani843.github.io" # the base hostname & protocol for your site

# Author information
author:
  name: "Research Team"
  email: "contact@example.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Kramdown settings for mathematical notation
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Navigation menu - will use relative_url in templates
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Methodology"
    url: /methodology/
  - title: "Results"
    url: /results/
  - title: "Conclusion"
    url: /conclusion/
  - title: "Contact"
    url: /contact/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Social media and external links
github_username: your-username
linkedin_username: your-profile

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Exclude from processing
exclude:
  - .gitignore
  - .git/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md

# Include custom assets
include:
  - _pages/
  - assets/

# Sass settings
sass:
  sass_dir: assets/css
  style: compressed

# Pagination
paginate: 5
paginate_path: "/page:num/"

# SEO settings
lang: en_US
locale: en_US

# MathJax configuration
mathjax:
  source: https://polyfill.io/v3/polyfill.min.js?features=es6
  config: 'MathJax = {tex: {inlineMath: [["$", "$"], ["\\(", "\\)"]], displayMath: [["$$", "$$"], ["\\[", "\\]"]]}, svg: {fontCache: "global"}};'

# Custom variables for the theme
project:
  name: "Mixed-Precision Multigrid Solvers"
  version: "1.0.0"
  github_repo: "https://github.com/tani843/Mixed_Precision_Multigrid_Solvers_for_PDEs"
  documentation: "https://tani843.github.io/Mixed_Precision_Multigrid_Solvers_for_PDEs"
  
# NOTE: benchmarks moved to _data/benchmarks.yml for proper data separation